project_id = "sxhgfmsnkuymkegomolp"

[functions.send-booking-email]
verify_jwt = false

[functions.send-cancellation-email]
verify_jwt = false

[functions.cancel-booking]
verify_jwt = false

[functions.send-reminder-emails]
verify_jwt = true
